### PR TITLE
Add matcher

### LINKED ISSUE #24: Add a problem matcher for dart analyse
Originally requested at https://github.com/cedx/setup-dart/issues/8

### PR DESCRIPTION
**Pull request by serverwentdown**
Closes #24

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks for the contribution! Can you add a screenshot(s) for what this would like like in a PR (I assume that's where the problem matcher results are surfaced)?

**Comment by serverwentdown** [comment]
# Dart
image
# Flutter
image

**Comment by kuhnroyal** [comment]
Can we add a flag for this? Already have other actions/matchers and would like to avoid double annotations.

**Comment by devoncarew** [comment]
Thanks for adding the screen shots!

I'm on the fence for this functionality. The additional highlighting of errors and warnings is nice - it helps to draw the eye to them - but the duplication of the severity text:

- `Error:    error - example/...`
- `Warning:  warning - example/...`

takes away from the UI.

Two thoughts:

- we could just have `dart analyze` customize it's output when run in a github context, to output custom formatting
- `dart analyze` does use ansi color codes when run from a terminal (see below), so perhaps we either need to adjust the terminal detection so that it outputs ansi codes for github, or, output ansi codes in either an interactive terminal context or a github context

Screen Shot 2022-08-09 at 2 34 29 PM

**Comment by serverwentdown** [comment]
From what I know about the other GitHub problem matchers, all of them have the same duplication: it's kinda not possible to remove it because by removing it, it won't be matched by the regular expression. The only other way to handle it is to build a full GitHub API client that generates it's own annotations. 

https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md

**Comment by devoncarew** [comment]
Hi @serverwentdown, coming back to this PR, I think this is out of scope for what we want to do with this action. Thank you for your contribution in any case.

For other people following along, this functionality can be provided by using an additional action. See for example https://github.com/leancodepl/dart-problem-matcher.

**Pull request closed without merging**
