### PR TITLE
Support main (aka edge) builds

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/dart-lang/setup-dart/issues/4

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
worth added a usage of this to the repo – just to sanity check?

**Comment by mit-mit** [comment]
Already did! See https://github.com/dart-lang/setup-dart/pull/16/files#diff-c6fe895eea1e566d8f6f9f7e5f045b702d9bff8e60bfaec2d412193bd802ab2aR18

**Comment by mit-mit** [comment]
And https://github.com/dart-lang/setup-dart/runs/1730214571?check_suite_focus=true

**Comment by kevmoo** [comment]
Land it! Tag it? Release it?

**Comment by mit-mit** [comment]
Just updated the readme, once that passes testing I'll merge it, and release as `@v0.3`

**Pull request merged**
